services:
  backend:
    build: ./backend
    container_name: devtinder-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_BASE_URL: http://3.27.149.19:3000
    container_name: devtinder-frontend
    restart: always
    ports:
      - "4173:4173"
    depends_on:
      - backend
